namespace NetBootDhcpTool.Core;

public static class Defaults
{
    public static void EnsureFiles(AppPaths paths)
    {
        paths.Ensure();
        if (!File.Exists(paths.SettingsFile)) JsonStore.Save(paths.SettingsFile, new AppSettings());
        if (!File.Exists(paths.ProfilesFile)) JsonStore.Save(paths.ProfilesFile, new List<NetworkProfile>());
        if (!File.Exists(paths.FavoritesFile))
        {
            FavoriteStore.Save(paths.FavoritesFile, DefaultFavorites());
        }
        else
        {
            var existing = FavoriteStore.Load(paths.FavoritesFile, migrateLegacy: true);
            var defaults = DefaultFavorites();
            var changed = false;
            foreach (var preset in defaults)
            {
                var current = existing.FirstOrDefault(x => x.Id.Equals(preset.Id, StringComparison.OrdinalIgnoreCase));
                if (current == null)
                {
                    existing.Add(preset);
                    changed = true;
                    continue;
                }

                // Upgrade the shipped BMC templates once, without overwriting a
                // user's separately-created favorite with the same display name.
                if (current.RemarkName.Equals("BMC preset", StringComparison.OrdinalIgnoreCase))
                {
                    current.IsPublicDefault = true;
                    current.Password = preset.Password;
                    current.PublicPassword = preset.Password;
                    current.Description = preset.Description;
                    current.MemoryText = preset.MemoryText;
                    current.CustomFields = preset.CustomFields;
                    changed = true;
                }
            }
            if (existing.Count == 0 || changed) FavoriteStore.Save(paths.FavoritesFile, existing);
        }
        var zh = Path.Combine(paths.I18nDirectory, "zh-CN.json");
        var en = Path.Combine(paths.I18nDirectory, "en-US.json");
        if (!File.Exists(zh)) JsonStore.Save(zh, Zh());
        if (!File.Exists(en)) JsonStore.Save(en, En());
    }

    public static Dictionary<string, string> Zh() => new()
    {
        ["app.title"] = "NetBoot DHCP Tool",
        ["language"] = "语言",
        ["refresh"] = "刷新",
        ["rollback"] = "回滚",
        ["export.results"] = "导出结果",
        ["diagnostics"] = "网卡诊断",
        ["safety.guide"] = "安全引导",
        ["package.logs"] = "支持包",
        ["theme"] = "主题",
        ["theme.light"] = "浅色主题",
        ["restart.adapter"] = "重启网卡",
        ["change.mac"] = "修改 MAC",
        ["open.logs"] = "打开日志",
        ["about"] = "关于",
        ["version"] = "版本",
        ["checking.update"] = "正在检查更新...",
        ["new.version"] = "有新版本！",
        ["latest.version"] = "已是最新版本",
        ["update.failed"] = "检查更新失败",
        ["adapter"] = "网卡",
        ["current.ip"] = "上次/当前 IP",
        ["mac"] = "MAC",
        ["gateway"] = "网关",
        ["status"] = "状态",
        ["auto.dhcp"] = "自动 DHCP",
        ["manual.scan"] = "手动 IP / 扫描",
        ["favorites"] = "收藏夹",
        ["profiles"] = "配置方案",
        ["history"] = "操作历史",
        ["static.routes"] = "静态路由",
        ["settings"] = "设置",
        ["server.ip"] = "本机 IP",
        ["subnet.mask"] = "子网掩码",
        ["pool.start"] = "起始地址",
        ["pool.end"] = "结束地址",
        ["dns"] = "DNS",
        ["target.ip"] = "对端 IP",
        ["lease.seconds"] = "租约秒数",
        ["start.dhcp"] = "开始 DHCP",
        ["stop.dhcp"] = "停止 DHCP",
        ["show.gateway"] = "+ 网关",
        ["show.dns"] = "+ DNS",
        ["fill.dhcp.range"] = "按网段填充",
        ["fill.target.ip"] = "填充目标 IP",
        ["isolated.confirm"] = "我确认当前网络为隔离调试网络",
        ["restore.stop"] = "停止后恢复原始 IP",
        ["apply.scan"] = "应用并扫描",
        ["preview.dhcp"] = "预览 DHCP",
        ["preview.scan"] = "预览扫描",
        ["preview.routes"] = "预览路由",
        ["stop.scan"] = "停止扫描",
        ["restore.scan"] = "恢复网卡",
        ["add.favorite"] = "加入收藏",
        ["new.favorite"] = "手动新增",
        ["template.favorite"] = "模板",
        ["import.favorite"] = "导入",
        ["export.favorite"] = "导出",
        ["favorite.columns"] = "列",
        ["open.favorite"] = "打开网页",
        ["delete"] = "删除",
        ["load"] = "加载",
        ["apply.and.scan"] = "应用并扫描",
        ["search"] = "搜索",
        ["clear.log"] = "清空显示",
        ["copy.log"] = "复制日志",
        ["copy.scan"] = "复制扫描结果",
        ["copy.history"] = "复制历史",
        ["history.search"] = "筛选",
        ["history.clear"] = "清空历史",
        ["profile.save.current"] = "保存当前方案",
        ["profile.load"] = "加载到表单",
        ["profile.compare"] = "对比当前",
        ["profile.duplicate"] = "复制方案",
        ["profile.import"] = "导入方案",
        ["profile.export"] = "导出方案",
        ["profile.delete"] = "删除方案",
        ["show.log"] = "展开日志",
        ["hide.log"] = "收起日志",
        ["log.auto.scroll"] = "自动滚底",
        ["use.local.ip"] = "使用本机 IP",
        ["warning.dhcp"] = "请确认当前网卡连接的是隔离调试网络，不要连接到办公网络、生产网络或已有 DHCP 的网络，否则可能造成 IP 冲突或网络异常。",
        ["blocked.wifi"] = "默认禁止在 Wi-Fi 网卡启动 DHCP。",
        ["blocked.gateway"] = "默认禁止在有默认网关的网卡启动 DHCP。",
        ["existing.dhcp"] = "检测到当前网络已有 DHCP 服务",
        ["blocked.virtual"] = "默认禁止在虚拟网卡启动 DHCP。",
        ["blocked.disconnected"] = "当前网卡未连接，不能启动 DHCP。",
        ["allow.wifi"] = "允许在 Wi-Fi 网卡启动 DHCP",
        ["allow.gateway"] = "允许在有默认网关的网卡启动 DHCP",
        ["allow.restart.any"] = "允许重启无线、虚拟、未连接等所有网卡",
        ["allow.mac.any"] = "允许修改无线、虚拟、未连接等所有网卡 MAC",
        ["detect.existing.dhcp"] = "启动前检测已有 DHCP 服务",
        ["save"] = "保存",
        ["add.route"] = "新增路由",
        ["remove.route"] = "删除选中",
        ["apply.routes"] = "应用路由",
        ["clear.applied.routes"] = "清除已应用",
        ["route.rules"] = "新增规则",
        ["route.current"] = "本机现有路由（只读）",
        ["route.destination"] = "目标网段",
        ["route.adapter"] = "使用网卡",
        ["route.next.hop"] = "网关（可选）",
        ["route.metric"] = "跃点",
        ["route.status"] = "状态",
        ["route.hint"] = "可新增多条 IPv4/IPv6 路由；单个地址按 /32 或 /128 处理，地址会规范化到网段边界。不同网卡允许使用同一前缀，但同一网卡同一前缀只能保留一条；网关必须在所选网卡直连网段内。跃点按接口跃点自动计算，预览会显示同前缀实际优先网卡；不同前缀按最长前缀优先。路由仅在本次运行期间有效，退出时自动清除，不允许新增默认路由。",
        ["dhcp.client.hint"] = "如果客户端 DHCP 超时，请按顺序尝试：重新获取 IP、禁用/启用客户端网卡、拔插对端网线、重启客户端网络服务或设备，并确认网线、交换机、网口指示灯正常。",
        ["dhcp.timeout.hint"] = "45 秒内没有收到客户端 DHCP 请求。请检查网线、交换机、网口指示灯，并在客户端重新获取 IP、禁用/启用网卡、拔插对端网线或重启客户端设备。",
        ["ok"] = "确定",
        ["cancel"] = "取消",
        ["help.open.history"] = "打开操作历史，查看最近一次结果和完整操作记录。",
        ["help.recovery.center"] = "查看本次运行残留的路由、网卡回滚备份和待恢复 MAC，并按需执行恢复。",
        ["help.clear.filter"] = "清除当前搜索和状态筛选，恢复显示全部内容。",
        ["filter.clear"] = "清除筛选",
        ["help.favorite.details.reveal"] = "显示当前收藏详情中的密码；显示后复制会再次确认。",
        ["recovery.banner"] = "有 {0} 项本次运行变更待处理：路由 {1} 条，MAC {2} 个。",
        ["recovery.title"] = "恢复中心",
        ["recovery.items.summary"] = "已保存的恢复项目。选择一项查看网卡身份与保存时间，然后显式恢复。",
        ["recovery.restore.selected"] = "恢复选中项目",
        ["recovery.no.items"] = "当前没有可恢复项目。",
        ["recovery.column.type"] = "类型",
        ["recovery.column.adapter"] = "网卡",
        ["recovery.column.identity"] = "身份",
        ["recovery.column.captured"] = "保存时间",
        ["recovery.column.details"] = "内容",
        ["recovery.column.status"] = "状态",
        ["recovery.kind.adapter"] = "网卡配置",
        ["recovery.kind.mac"] = "MAC 地址",
        ["recovery.kind.route"] = "静态路由",
        ["recovery.status.available"] = "可恢复",
        ["recovery.status.unavailable"] = "网卡不可用或身份不匹配",
        ["recovery.entry.adapter.summary"] = "{0}；IPv4 {1}/{2}；网关 {3}",
        ["recovery.entry.mac.summary"] = "原始 MAC：{0}",
        ["recovery.entry.route.summary"] = "目标 {0}；下一跳 {1}；跃点 {2}",
        ["recovery.entry.session"] = "当前会话",
        ["recovery.operation.running"] = "正在恢复选中项目…",
        ["recovery.restore.adapter.confirm"] = "要恢复 {0} 在 {1} 保存的 IPv4 配置吗？这会覆盖该网卡当前的 IPv4 设置。",
        ["dhcp.enabled"] = "自动获取",
        ["dhcp.disabled"] = "固定 IPv4",
        ["recovery.restore.route.confirm"] = "将只删除本工具记录的这条会话路由：\n{0}\n确认继续？",
        ["recovery.restore.mac.confirm"] = "将把 {0} 的 MAC 地址恢复为 {1}。确认继续？",
        ["migration.warning.title"] = "旧数据迁移需要处理",
        ["migration.warning.body"] = "部分旧数据未能复制到用户数据目录。原文件仍保留，请查看日志并确认后再继续：\n{0}",
        ["recovery.summary"] = "这里集中显示可回滚的网卡备份、本次运行创建的静态路由和待恢复的 MAC。所有恢复动作都需要你明确点击确认。",
        ["recovery.routes"] = "本次运行静态路由：{0} 条",
        ["recovery.adapter"] = "网卡回滚备份：{0} 条",
        ["recovery.mac"] = "待恢复 MAC：{0} 个",
        ["recovery.restore.routes"] = "清理本次路由",
        ["recovery.restore.adapter"] = "恢复选中网卡",
        ["recovery.restore.mac"] = "恢复待处理 MAC",
        ["recovery.close"] = "关闭",
        ["recovery.no.adapter"] = "请先在主窗口选择有回滚备份的网卡。",
        ["last.operation.none"] = "最近操作：暂无",
        ["last.operation"] = "最近操作：{0} · {1} · {2}",
        ["credential.hidden"] = "已隐藏",
        ["credential.unavailable"] = "不可用 / 需重新输入",
        ["credential.reveal"] = "显示密码",
        ["credential.hide"] = "隐藏密码",
        ["credential.copy"] = "复制",
        ["credential.copy.confirm"] = "复制内容包含密码。密码会进入系统剪贴板，确定继续吗？",
        ["selection.favorite"] = "请选择收藏配置后再加载、应用或打开。",
        ["selection.profile"] = "请选择配置方案后再加载、对比、复制或删除。",
        ["selection.route"] = "请选择路由草稿后再删除。",
        ["verify.static.failed"] = "变更后校验失败：网卡当前状态与目标配置不一致。",
        ["verify.restore.failed"] = "恢复后校验失败：网卡当前状态与保存的原始配置不一致。",
        ["about.details"] = "IPv4 DHCP / 扫描 / 静态路由 / 收藏夹\n作者：Joel & Codex\n邮箱：1406829360@qq.com",
        ["help.language"] = "选择自动、中文或 English 界面语言。",
        ["help.favorite.search"] = "按名称、设备、序列号、备注或 IP 筛选收藏夹。",
        ["help.confirm.isolated"] = "确认当前网卡连接的是隔离调试网络；启动 DHCP 前必须勾选。",
        ["help.restore.stop"] = "停止 DHCP 后恢复启动前保存的网卡 IP 配置。",
        ["help.lease.grid"] = "显示 DHCP 租约、客户端 MAC/IP、在线状态、Ping 延迟和最后上线时间。",
        ["help.scan.grid"] = "显示手动扫描发现的 IP、连通性、网页入口、MAC、主机名和最后发现时间。",
        ["help.route.grid"] = "新增 IPv4/IPv6 路由规则；可填写单个地址或 CIDR 网段，选择任意本地网卡，优先级由工具自动计算。",
        ["help.route.current.grid"] = "显示所有本地网卡当前 IPv4/IPv6 路由，只读用于确认现有路径，不会被本工具修改。",
        ["help.favorite.grid"] = "显示收藏夹的设备、账号、密码、网络参数、备注和自定义字段。",
        ["help.tab.dhcp"] = "自动 DHCP：在隔离网络中为客户端提供地址租约。",
        ["help.tab.scan"] = "手动 IP / 扫描：给选中网卡配置临时 IP，并探测目标或网段。",
        ["help.tab.routes"] = "静态路由：新增临时 IPv4/IPv6 规则，并查看所有网卡当前路由。",
        ["help.tab.favorites"] = "收藏夹：保存和复用网络扫描参数及服务器带外管理信息。",
        ["help.tab.settings"] = "设置：调整 DHCP 安全开关、网卡操作范围和退出恢复行为。",
        ["help.title"] = "帮助",
        ["help.adapter.selector"] = "当前选择的网卡；顶部选择会影响 DHCP、手动扫描和网卡操作。静态路由页会显示所有网卡的当前路由。",
        ["help.current.ip"] = "当前网卡的 IPv4 地址；如果本工具修改过地址，同时显示最近一次记录的地址。",
        ["help.mac.value"] = "当前网卡的 MAC 地址；修改 MAC 后会在这里刷新显示。",
        ["help.gateway.value"] = "当前网卡检测到的默认网关；有网关的网卡默认禁止启动 DHCP。",
        ["help.status.value"] = "网卡连接状态，例如 Up 表示已启用，Disconnected/Down 表示未连接或已停用。",
        ["help.server.ip"] = "DHCP 服务端或手动扫描使用的本机 IPv4 地址。",
        ["help.subnet.mask"] = "本机 IPv4 子网掩码，用于确定扫描网段。",
        ["help.pool.start"] = "DHCP 地址池起始地址。",
        ["help.pool.end"] = "DHCP 地址池结束地址。",
        ["help.lease.seconds"] = "DHCP 租约有效期，单位为秒。",
        ["help.manual.ip"] = "手动扫描前要配置到选中网卡的本机 IPv4 地址。",
        ["help.manual.mask"] = "手动扫描使用的本机 IPv4 子网掩码。",
        ["help.manual.target.ip"] = "填写后只持续探测这个对端 IP；留空则扫描整个子网。",
        ["help.refresh"] = "刷新网卡列表，并读取本机所有网卡的当前 IPv4 地址、状态和静态路由；不会主动修改网络配置。",
        ["help.rollback"] = "回滚选中网卡最近一次保存的网络配置；执行前请确认目标网卡。",
        ["help.export.results"] = "将当前 DHCP 租约或扫描结果导出为 CSV 文件。",
        ["help.diagnostics"] = "查看选中网卡的名称、状态、IP、网关、DNS、MAC，以及是否为 Wi-Fi 或虚拟网卡。",
        ["help.safety.guide"] = "查看并确认网络变更的安全边界；首次确认前，DHCP、IP、路由、MAC 和网卡重启操作会保持锁定。",
        ["help.package.logs"] = "将当前运行日志、设置和备份打包为 ZIP，便于问题分析；不会自动发送。支持包默认脱敏 IP、MAC 和 IPv6 地址。",
        ["help.theme"] = "切换浅色或深色界面主题。",
        ["help.open.logs"] = "打开本地日志目录。",
        ["help.about"] = "查看版本、作者和联系方式。",
        ["help.change.mac"] = "修改选中网卡的 MAC 地址；支持手动输入或随机生成，并可选择正常退出时还原。",
        ["help.restart.adapter"] = "禁用后重新启用选中网卡；期间该网卡通信会短暂中断。",
        ["help.clear.log"] = "清空窗口中显示的日志，不会删除磁盘上的日志文件。",
        ["help.copy.log"] = "复制当前窗口显示的日志文本到剪贴板。",
        ["help.show.gateway"] = "显示可选的 DHCP 网关输入框；不填写时不会下发网关。",
        ["help.show.dns"] = "显示可选的 DHCP DNS 输入框；不填写时不会下发 DNS。",
        ["help.fill.dhcp.range"] = "根据本机 IP 和掩码生成 DHCP 服务端及地址池起止地址；生成后仍可手动修改。",
        ["help.fill.target.ip"] = "根据本机 IP 和掩码生成一个附近的目标 IP；生成后仍可手动修改。",
        ["help.toggle.log"] = "展开或收起本窗口的运行日志。磁盘日志不会受影响。",
        ["help.preview.dhcp"] = "只预览 DHCP 参数、地址池和网卡变更，不会修改系统。",
        ["help.preview.scan"] = "只预览手动扫描将使用的本机地址、网段和目标，不会修改系统。",
        ["help.preview.routes"] = "只读取并预览路由计划、出口和综合跃点，不会写入系统。",
        ["help.copy.scan"] = "复制当前筛选后的扫描结果；也可使用 Ctrl+C 复制选中行。",
        ["help.scan.filter"] = "按 IP、MAC、主机名、状态或备注筛选扫描结果。",
        ["help.cancel.operation"] = "取消当前可取消的扫描、路由或网卡操作；已经完成的系统变更会按回滚策略处理。",
        ["help.profile.save.current"] = "将当前 DHCP、手动扫描和路由草稿保存为本地配置方案，不会自动应用。",
        ["help.profile.load"] = "把选中的配置方案加载到表单和路由草稿中，不会自动应用网络变更。",
        ["help.profile.compare"] = "对比选中方案与当前表单，显示 DHCP、扫描和路由草稿差异，不会修改任何内容。",
        ["help.profile.duplicate"] = "复制选中的配置方案并生成一个新的本地方案。",
        ["help.profile.import"] = "从 JSON 导入不含凭据的配置方案。",
        ["help.profile.export"] = "导出不含凭据的配置方案 JSON。",
        ["help.profile.delete"] = "删除选中的本地配置方案。",
        ["help.profile.save"] = "确认方案名称和说明并保存。",
        ["help.profile.cancel"] = "取消保存配置方案。",
        ["help.history.copy"] = "复制当前筛选后的操作历史内容。",
        ["help.history.search"] = "按操作、范围、状态、详情、IP 或 MAC 筛选操作历史。",
        ["help.history.clear"] = "清空本地操作历史记录；运行日志和网络配置不受影响。",
        ["help.session.status"] = "显示权限、当前网卡、当前业务状态以及本次运行是否存在待清理或恢复的变更。",
        ["help.start.dhcp"] = "在确认隔离网络后启动 DHCP 服务；可能影响所选网卡上的客户端。",
        ["help.stop.dhcp"] = "停止 DHCP 服务，并按设置决定是否恢复原始网卡配置。",
        ["help.apply.scan"] = "先把手动 IP 和掩码应用到选中网卡，再扫描目标 IP 或整个网段。",
        ["help.stop.scan"] = "停止当前手动扫描并保留已经得到的结果。",
        ["help.restore.scan"] = "恢复本次运行中记录的选中网卡原始 IP 配置。",
        ["help.add.favorite.scan"] = "把当前手动扫描参数加入收藏夹。",
        ["help.add.route"] = "新增一条 IPv4/IPv6 静态路由草稿；可填写单个地址或 CIDR 网段，不会立即写入系统。",
        ["help.remove.route"] = "删除当前选中的静态路由草稿；已存在系统路由不会被删除。",
        ["help.apply.routes"] = "应用本次新增规则；不修改已有路由，若目标网段存在更具体冲突会阻止应用，同前缀会自动计算更高优先级。",
        ["help.clear.applied.routes"] = "清除本次运行已应用并记录的静态路由。",
        ["help.new.favorite"] = "手动创建收藏夹条目。",
        ["help.template.favorite"] = "从常见服务器厂商模板创建 BMC 收藏夹。",
        ["help.import.favorite"] = "从 JSON 文件导入收藏夹，并合并到本地收藏夹。",
        ["help.export.favorite"] = "将收藏夹导出为不含密码的 JSON 文件。",
        ["help.favorite.columns"] = "选择收藏夹表格显示的列；可拖动表头调整顺序。",
        ["help.open.favorite"] = "用收藏夹目标 IP 打开 HTTP 或 HTTPS 管理页面。",
        ["help.load.favorite"] = "把选中收藏夹的本机 IP、掩码和对端 IP 加载到手动扫描页，不执行扫描。",
        ["help.apply.favorite"] = "加载收藏夹后立即配置网卡并执行一次手动扫描。",
        ["help.delete.favorite"] = "删除选中的收藏夹；删除前请确认是否还有需要保留的备注。",
        ["help.save.settings"] = "保存设置中的安全开关和恢复选项。",
        ["support.redact"] = "支持包默认脱敏网络地址",
        ["help.favorite.ok"] = "确认并保存收藏夹字段和自定义字段；名称、本机 IP、掩码为必填。",
        ["help.favorite.cancel"] = "取消编辑并关闭窗口，不保存本次修改。",
        ["help.favorite.add.field"] = "新增一个自定义字段，并进入编辑状态。",
        ["help.favorite.delete.field"] = "删除当前选中的自定义字段。",
        ["help.mac.cancel"] = "取消修改 MAC 并关闭窗口。",
        ["help.mac.apply"] = "校验并应用输入的 MAC 地址；只有正常退出且勾选还原时才会恢复原 MAC。",
        ["help.mac.random"] = "生成一个本地管理、单播的随机 MAC 地址。",
        ["help.dialog.cancel"] = "取消当前确认或操作。",
        ["help.dialog.ok"] = "确认当前提示并继续操作。",
        ["help.template.favorite.add"] = "将选中的厂商模板加入收藏夹。",
        ["help.favorite.columns.close"] = "关闭收藏夹列设置窗口。",
        ["help.favorite.fields.copy"] = "复制当前收藏夹的自定义字段内容。",
        ["help.favorite.fields.close"] = "关闭自定义字段查看窗口。",
        ["help.favorite.details.copy"] = "复制当前收藏夹的详细信息。",
        ["help.favorite.details.close"] = "关闭收藏夹详情窗口。"
    };

    public static Dictionary<string, string> En() => new()
    {
        ["app.title"] = "NetBoot DHCP Tool",
        ["language"] = "Language",
        ["refresh"] = "Refresh",
        ["rollback"] = "Rollback",
        ["export.results"] = "Export Results",
        ["diagnostics"] = "Adapter Diagnostics",
        ["safety.guide"] = "Safety Guide",
        ["package.logs"] = "Support Package",
        ["theme"] = "Theme",
        ["theme.light"] = "Light Theme",
        ["restart.adapter"] = "Restart Adapter",
        ["change.mac"] = "Change MAC",
        ["open.logs"] = "Open Logs",
        ["about"] = "About",
        ["version"] = "Version",
        ["checking.update"] = "Checking for updates...",
        ["new.version"] = "New version available!",
        ["latest.version"] = "Up to date",
        ["update.failed"] = "Update check failed",
        ["adapter"] = "Adapter",
        ["current.ip"] = "Last / Current IP",
        ["mac"] = "MAC",
        ["gateway"] = "Gateway",
        ["status"] = "Status",
        ["auto.dhcp"] = "Auto DHCP",
        ["manual.scan"] = "Manual IP / Scan",
        ["favorites"] = "Favorites",
        ["profiles"] = "Profiles",
        ["history"] = "Operation History",
        ["static.routes"] = "Static Routes",
        ["settings"] = "Settings",
        ["server.ip"] = "Local IP",
        ["subnet.mask"] = "Subnet Mask",
        ["pool.start"] = "Pool Start",
        ["pool.end"] = "Pool End",
        ["dns"] = "DNS",
        ["target.ip"] = "Target IP",
        ["lease.seconds"] = "Lease Seconds",
        ["start.dhcp"] = "Start DHCP",
        ["stop.dhcp"] = "Stop DHCP",
        ["show.gateway"] = "+ Gateway",
        ["show.dns"] = "+ DNS",
        ["fill.dhcp.range"] = "Fill from subnet",
        ["fill.target.ip"] = "Fill target IP",
        ["isolated.confirm"] = "I confirm this is an isolated test network",
        ["restore.stop"] = "Restore original IP after stop",
        ["apply.scan"] = "Apply and Scan",
        ["preview.dhcp"] = "Preview DHCP",
        ["preview.scan"] = "Preview Scan",
        ["preview.routes"] = "Preview Routes",
        ["stop.scan"] = "Stop Scan",
        ["restore.scan"] = "Restore Adapter",
        ["add.favorite"] = "Add Favorite",
        ["new.favorite"] = "New",
        ["template.favorite"] = "Templates",
        ["import.favorite"] = "Import",
        ["export.favorite"] = "Export",
        ["favorite.columns"] = "Columns",
        ["open.favorite"] = "Open Web",
        ["delete"] = "Delete",
        ["load"] = "Load",
        ["apply.and.scan"] = "Apply and Scan",
        ["search"] = "Search",
        ["clear.log"] = "Clear",
        ["copy.log"] = "Copy Log",
        ["copy.scan"] = "Copy Scan Results",
        ["copy.history"] = "Copy History",
        ["history.search"] = "Filter",
        ["history.clear"] = "Clear History",
        ["profile.save.current"] = "Save Current",
        ["profile.load"] = "Load to Form",
        ["profile.compare"] = "Compare Current",
        ["profile.duplicate"] = "Duplicate",
        ["profile.import"] = "Import",
        ["profile.export"] = "Export",
        ["profile.delete"] = "Delete",
        ["show.log"] = "Show Log",
        ["hide.log"] = "Hide Log",
        ["log.auto.scroll"] = "Auto-scroll",
        ["use.local.ip"] = "Use local IP",
        ["warning.dhcp"] = "Please make sure the selected adapter is connected to an isolated test network. Do not use this DHCP server on an office network, production network, or a network that already has DHCP service. Otherwise, IP conflicts or network outages may occur.",
        ["blocked.wifi"] = "Starting DHCP on Wi-Fi is blocked by default.",
        ["blocked.gateway"] = "Starting DHCP on an adapter with a default gateway is blocked by default.",
        ["existing.dhcp"] = "Existing DHCP service detected",
        ["blocked.virtual"] = "Starting DHCP on a virtual adapter is blocked by default.",
        ["blocked.disconnected"] = "The selected adapter is disconnected. DHCP cannot start.",
        ["allow.wifi"] = "Allow DHCP on Wi-Fi",
        ["allow.gateway"] = "Allow DHCP on adapter with default gateway",
        ["allow.restart.any"] = "Allow restarting wireless, virtual, disconnected, and all other adapters",
        ["allow.mac.any"] = "Allow changing MAC on wireless, virtual, disconnected, and all other adapters",
        ["detect.existing.dhcp"] = "Detect existing DHCP before start",
        ["save"] = "Save",
        ["add.route"] = "Add Route",
        ["remove.route"] = "Remove Selected",
        ["apply.routes"] = "Apply Routes",
        ["clear.applied.routes"] = "Clear Applied",
        ["route.rules"] = "New Rules",
        ["route.current"] = "Current System Routes (Read-only)",
        ["route.destination"] = "Destination",
        ["route.adapter"] = "Adapter",
        ["route.next.hop"] = "Gateway (optional)",
        ["route.metric"] = "Metric",
        ["route.status"] = "Status",
        ["route.hint"] = "Add multiple IPv4/IPv6 routes; a single address is treated as /32 or /128 and host bits are normalized. The same prefix may use different adapters, but only one rule per prefix is allowed on one adapter; a gateway must be on-link for the selected adapter. Metrics are calculated from interface metrics and the preview shows the same-prefix winner; overlapping prefixes use longest-prefix match. Routes are temporary, removed on exit, and default routes are not allowed.",
        ["dhcp.client.hint"] = "If the client DHCP request times out, try renew IP, disable/enable the client adapter, unplug/replug the client cable, restart the client network service or device, and check cable, switch, and link lights.",
        ["dhcp.timeout.hint"] = "No client DHCP request was received within 45 seconds. Check cable, switch, and link lights, then renew IP, disable/enable the client adapter, unplug/replug the client cable, or restart the client device.",
        ["ok"] = "OK",
        ["cancel"] = "Cancel",
        ["help.open.history"] = "Open Operation History to review the latest result and the complete local record.",
        ["help.recovery.center"] = "Review leftover routes, adapter rollback snapshots, and MAC restorations, then recover them as needed.",
        ["help.clear.filter"] = "Clear the current search and status filters to show all items.",
        ["filter.clear"] = "Clear filter",
        ["help.favorite.details.reveal"] = "Reveal the password in Favorite Details; copying it requires another confirmation.",
        ["recovery.banner"] = "{0} session changes need attention: {1} route(s), {2} MAC restoration(s).",
        ["recovery.title"] = "Recovery Center",
        ["recovery.items.summary"] = "Saved recovery items. Select one to review its adapter identity and capture time before explicitly restoring it.",
        ["recovery.restore.selected"] = "Restore selected item",
        ["recovery.no.items"] = "There are no recovery items right now.",
        ["recovery.column.type"] = "Type",
        ["recovery.column.adapter"] = "Adapter",
        ["recovery.column.identity"] = "Identity",
        ["recovery.column.captured"] = "Saved",
        ["recovery.column.details"] = "Details",
        ["recovery.column.status"] = "Status",
        ["recovery.kind.adapter"] = "Adapter config",
        ["recovery.kind.mac"] = "MAC address",
        ["recovery.kind.route"] = "Static route",
        ["recovery.status.available"] = "Available",
        ["recovery.status.unavailable"] = "Adapter unavailable or identity mismatch",
        ["recovery.entry.adapter.summary"] = "{0}; IPv4 {1}/{2}; gateway {3}",
        ["recovery.entry.mac.summary"] = "Original MAC: {0}",
        ["recovery.entry.route.summary"] = "Destination {0}; next hop {1}; metric {2}",
        ["recovery.entry.session"] = "Current session",
        ["recovery.operation.running"] = "Restoring selected item...",
        ["recovery.restore.adapter.confirm"] = "Restore {0}'s IPv4 configuration saved on {1}? This will overwrite the adapter's current IPv4 settings.",
        ["dhcp.enabled"] = "DHCP enabled",
        ["dhcp.disabled"] = "Static IPv4",
        ["recovery.restore.route.confirm"] = "Only this session route recorded by the tool will be removed:\n{0}\nContinue?",
        ["recovery.restore.mac.confirm"] = "Restore {0}'s MAC address to {1}?",
        ["migration.warning.title"] = "Legacy data migration needs attention",
        ["migration.warning.body"] = "Some legacy files could not be copied to the user data folder. The original files were retained. Review the log before continuing:\n{0}",
        ["recovery.summary"] = "This center lists rollback-capable adapter snapshots, static routes created in this run, and MAC restorations. Every recovery action requires an explicit confirmation.",
        ["recovery.routes"] = "Static routes created in this run: {0}",
        ["recovery.adapter"] = "Adapter rollback snapshots: {0}",
        ["recovery.mac"] = "MAC restorations pending: {0}",
        ["recovery.restore.routes"] = "Clear session routes",
        ["recovery.restore.adapter"] = "Restore selected adapter",
        ["recovery.restore.mac"] = "Restore pending MACs",
        ["recovery.close"] = "Close",
        ["recovery.no.adapter"] = "Select an adapter with a rollback snapshot in the main window first.",
        ["last.operation.none"] = "Latest operation: none",
        ["last.operation"] = "Latest operation: {0} · {1} · {2}",
        ["credential.hidden"] = "Hidden",
        ["credential.unavailable"] = "Unavailable / enter again",
        ["credential.reveal"] = "Show password",
        ["credential.hide"] = "Hide password",
        ["credential.copy"] = "Copy",
        ["credential.copy.confirm"] = "The copied content includes the password. It will be placed in the system clipboard. Continue?",
        ["selection.favorite"] = "Select a favorite before loading, applying, or opening it.",
        ["selection.profile"] = "Select a profile before loading, comparing, duplicating, or deleting it.",
        ["selection.route"] = "Select a route draft before removing it.",
        ["verify.static.failed"] = "Post-change verification failed: the adapter does not match the target configuration.",
        ["verify.restore.failed"] = "Restore verification failed: the adapter does not match the saved original configuration.",
        ["about.details"] = "IPv4 DHCP / Scan / Static Routes / Favorites\nAuthors: Joel & Codex\nEmail: 1406829360@qq.com",
        ["help.language"] = "Choose Auto, Chinese, or English for the interface language.",
        ["help.favorite.search"] = "Filter Favorites by name, device, serial number, remark, or IP.",
        ["help.confirm.isolated"] = "Confirm that the selected adapter is connected to an isolated test network. This must be checked before DHCP starts.",
        ["help.restore.stop"] = "Restore the adapter IP configuration saved before DHCP started.",
        ["help.lease.grid"] = "Shows DHCP leases, client MAC/IP, online state, ping latency, and last-online time.",
        ["help.scan.grid"] = "Shows discovered IPs, reachability, web links, MAC, hostname, and last-seen time from a manual scan.",
        ["help.route.grid"] = "Creates new IPv4/IPv6 route rules. Enter a single address or CIDR network, select any local adapter, and let the tool calculate priority.",
        ["help.route.current.grid"] = "Shows current IPv4/IPv6 routes from all local adapters. This view is read-only and existing routes are not modified.",
        ["help.favorite.grid"] = "Shows Favorite device, account, password, network parameters, notes, and custom fields.",
        ["help.tab.dhcp"] = "Auto DHCP: provide address leases to clients on an isolated network.",
        ["help.tab.scan"] = "Manual IP / Scan: configure a temporary IP on the selected adapter and probe a target or network.",
        ["help.tab.routes"] = "Static Routes: add temporary IPv4/IPv6 rules and view current routes from all adapters.",
        ["help.tab.favorites"] = "Favorites: save and reuse scan parameters and server out-of-band management details.",
        ["help.tab.settings"] = "Settings: adjust DHCP safety switches, adapter action scope, and exit restoration behavior.",
        ["help.title"] = "Help",
        ["help.adapter.selector"] = "The selected adapter. This selection affects DHCP, manual scanning, and adapter actions. The Static Routes page displays current routes from all adapters.",
        ["help.current.ip"] = "The selected adapter's IPv4 address. If this tool changed it, the most recently recorded address is also shown.",
        ["help.mac.value"] = "The selected adapter's current MAC address. It refreshes here after a MAC change.",
        ["help.gateway.value"] = "The default gateway detected on the selected adapter. DHCP startup is blocked by default when a gateway exists.",
        ["help.status.value"] = "Adapter connection state. Up means enabled; Disconnected or Down means unavailable or disabled.",
        ["help.server.ip"] = "The local IPv4 address used by the DHCP server or manual scan.",
        ["help.subnet.mask"] = "The local IPv4 subnet mask used to determine the scan network.",
        ["help.pool.start"] = "The first address in the DHCP pool.",
        ["help.pool.end"] = "The last address in the DHCP pool.",
        ["help.lease.seconds"] = "The DHCP lease lifetime in seconds.",
        ["help.manual.ip"] = "The local IPv4 address to apply to the selected adapter before a manual scan.",
        ["help.manual.mask"] = "The local IPv4 subnet mask used by the manual scan.",
        ["help.manual.target.ip"] = "When filled, probe only this target IP continuously; when empty, scan the whole subnet.",
        ["help.refresh"] = "Refresh the adapter list and read current IPv4 addresses, states, and static routes from all local adapters. It does not change network configuration.",
        ["help.rollback"] = "Restore the most recently saved network configuration for the selected adapter. Confirm the target before continuing.",
        ["help.export.results"] = "Export the current DHCP leases or scan results to a CSV file.",
        ["help.diagnostics"] = "View the selected adapter's name, state, IP, gateway, DNS, MAC, and Wi-Fi or virtual status.",
        ["help.safety.guide"] = "Review and acknowledge the network-change safety boundary; DHCP, IP, route, MAC, and adapter-restart actions remain locked until the first acknowledgement.",
        ["help.package.logs"] = "Create a ZIP containing runtime logs, settings, and backups for troubleshooting. Nothing is sent automatically; IP, MAC, and IPv6 addresses are redacted by default.",
        ["help.theme"] = "Switch between the light and dark interface themes.",
        ["help.open.logs"] = "Open the local runtime log folder.",
        ["help.about"] = "View the version, authors, and contact information.",
        ["help.change.mac"] = "Change the selected adapter's MAC address using manual input or a generated value, with an option to restore it on normal exit.",
        ["help.restart.adapter"] = "Disable and re-enable the selected adapter. Its traffic will be interrupted briefly.",
        ["help.clear.log"] = "Clear the log text displayed in this window. Files on disk are not deleted.",
        ["help.copy.log"] = "Copy the log text currently displayed in this window to the clipboard.",
        ["help.show.gateway"] = "Show the optional DHCP gateway field. No gateway is sent when it is empty.",
        ["help.show.dns"] = "Show the optional DHCP DNS field. No DNS value is sent when it is empty.",
        ["help.fill.dhcp.range"] = "Generate the DHCP server and pool range from the local IP and mask. You can still edit the generated values.",
        ["help.fill.target.ip"] = "Generate a nearby target IP from the local IP and mask. You can still edit the generated value.",
        ["help.toggle.log"] = "Expand or collapse the runtime log shown in this window. Disk log files are not affected.",
        ["help.preview.dhcp"] = "Preview DHCP parameters, pool, and adapter changes without modifying the system.",
        ["help.preview.scan"] = "Preview the local address, subnet, and target for a manual scan without modifying the system.",
        ["help.preview.routes"] = "Read and preview the route plan, exits, and effective metrics without writing to the system.",
        ["help.copy.scan"] = "Copy the currently filtered scan results; Ctrl+C also copies selected rows.",
        ["help.scan.filter"] = "Filter scan results by IP, MAC, hostname, status, or remark.",
        ["help.cancel.operation"] = "Cancel a cancellable scan, route, or adapter operation; completed system changes follow the rollback policy.",
        ["help.profile.save.current"] = "Save current DHCP, manual scan, and route drafts as a local profile without applying them.",
        ["help.profile.load"] = "Load the selected profile into forms and route drafts without applying network changes.",
        ["help.profile.compare"] = "Compare the selected profile with the current forms and show DHCP, scan, and route-draft differences without changing anything.",
        ["help.profile.duplicate"] = "Duplicate the selected local profile as a new profile.",
        ["help.profile.import"] = "Import credential-free network profiles from JSON.",
        ["help.profile.export"] = "Export credential-free network profiles to JSON.",
        ["help.profile.delete"] = "Delete the selected local network profile.",
        ["help.profile.save"] = "Confirm the profile name and description and save it.",
        ["help.profile.cancel"] = "Cancel saving the network profile.",
        ["help.history.copy"] = "Copy the currently filtered operation history.",
        ["help.history.search"] = "Filter operation history by operation, scope, status, detail, IP, or MAC.",
        ["help.history.clear"] = "Clear local operation history; runtime logs and network configuration are not affected.",
        ["help.session.status"] = "Shows permissions, the selected adapter, the current workflow state, and whether this run has changes pending cleanup or restoration.",
        ["help.start.dhcp"] = "Start the DHCP service after confirming an isolated network. It may affect clients on the selected adapter.",
        ["help.stop.dhcp"] = "Stop the DHCP service and restore the original adapter configuration according to the setting.",
        ["help.apply.scan"] = "Apply the manual IP and mask to the selected adapter, then scan the target IP or the whole subnet.",
        ["help.stop.scan"] = "Stop the current manual scan and keep the results already collected.",
        ["help.restore.scan"] = "Restore the original IP configuration recorded for the selected adapter during this run.",
        ["help.add.favorite.scan"] = "Add the current manual-scan parameters to Favorites.",
        ["help.add.route"] = "Add an IPv4/IPv6 static-route draft. Enter a single address or CIDR network; it does not write to Windows immediately.",
        ["help.remove.route"] = "Remove the selected static-route draft. Existing system routes are not removed.",
        ["help.apply.routes"] = "Apply the new rules without modifying existing routes. More-specific conflicts are blocked and same-prefix priority is calculated automatically.",
        ["help.clear.applied.routes"] = "Remove static routes applied and recorded by this run.",
        ["help.new.favorite"] = "Create a Favorite entry manually.",
        ["help.template.favorite"] = "Create a BMC Favorite from a common server-vendor template.",
        ["help.import.favorite"] = "Import Favorites from JSON and merge them into the local collection.",
        ["help.export.favorite"] = "Export Favorites to a JSON file without passwords.",
        ["help.favorite.columns"] = "Choose visible Favorite columns and drag headers to reorder them.",
        ["help.open.favorite"] = "Open the Favorite target IP in an HTTP or HTTPS management page.",
        ["help.load.favorite"] = "Load the selected Favorite's local IP, mask, and target IP into Manual Scan without scanning.",
        ["help.apply.favorite"] = "Load the Favorite, configure the adapter, and run one manual scan.",
        ["help.delete.favorite"] = "Delete the selected Favorite. Confirm that any notes are no longer needed.",
        ["help.save.settings"] = "Save the safety switches and restoration options in Settings.",
        ["support.redact"] = "Redact network addresses in support package by default",
        ["help.favorite.ok"] = "Validate and save Favorite fields and custom fields. Name, local IP, and mask are required.",
        ["help.favorite.cancel"] = "Cancel editing and close the window without saving this edit.",
        ["help.favorite.add.field"] = "Add a custom field and enter edit mode.",
        ["help.favorite.delete.field"] = "Delete the selected custom field.",
        ["help.mac.cancel"] = "Cancel the MAC change and close the window.",
        ["help.mac.apply"] = "Validate and apply the entered MAC address. Restoration occurs only on normal exit when enabled.",
        ["help.mac.random"] = "Generate a locally administered, unicast random MAC address.",
        ["help.dialog.cancel"] = "Cancel the current confirmation or operation.",
        ["help.dialog.ok"] = "Confirm the current message and continue.",
        ["help.template.favorite.add"] = "Add the selected vendor template to Favorites.",
        ["help.favorite.columns.close"] = "Close the Favorite column settings window.",
        ["help.favorite.fields.copy"] = "Copy the current Favorite's custom-field contents.",
        ["help.favorite.fields.close"] = "Close the custom-fields viewer.",
        ["help.favorite.details.copy"] = "Copy the current Favorite's detailed information.",
        ["help.favorite.details.close"] = "Close the Favorite details window."
    };

    public static List<FavoriteConfig> DefaultFavorites()
    {
        var now = DateTime.Now;
        return
        [
            Bmc("Dell iDRAC legacy default", "Dell", "192.168.0.120", "root", "calvin", "公开旧型号默认值；新型号通常使用机身标签上的唯一密码。", "Public legacy default; newer models commonly use a unique chassis-label password.", "preset-dell-idrac", now),
            Bmc("HPE iLO default", "HPE", "192.168.0.120", "Administrator", "见机身标签（8位字符）", "默认静态地址和账号公开，但密码按服务器机身标签/型号变化。", "The default address and username are documented; the password varies by model and chassis label.", "preset-hpe-ilo", now),
            Bmc("Lenovo XCC default", "Lenovo", "192.168.70.125", "USERID", "PASSW0RD", "公开初始账号；首次登录后必须修改。", "Published initial account; change it on first login.", "preset-lenovo-xcc", now),
            Bmc("Supermicro IPMI legacy default", "Supermicro", "192.168.100.100", "ADMIN", "ADMIN", "旧型号公开默认值；新产品通常使用主板/机箱标签唯一密码。", "Legacy public default; newer products commonly use a unique motherboard/chassis-label password.", "preset-supermicro-ipmi", now),
            Bmc("Inspur BMC reference", "Inspur", "192.168.1.100", "admin", "以型号手册/标签为准", "不同浪潮型号默认值可能不同，仅作公开资料索引。", "Defaults vary by Inspur model; verify against the model manual or label.", "preset-inspur-bmc", now),
            Bmc("Huawei iBMC V3", "Huawei", "192.168.2.100", "root", "Huawei12#$", "华为 iBMC V3 公开默认值；首次登录后修改。", "Huawei iBMC V3 published default; change it after first login.", "preset-huawei-ibmc-v3", now),
            Bmc("Huawei iBMC V5", "Huawei", "192.168.2.100", "Administrator", "Admin@9000", "华为 iBMC V5 公开默认值；首次登录后修改。", "Huawei iBMC V5 published default; change it after first login.", "preset-huawei-ibmc-v5", now),
            Bmc("H3C HDM default", "H3C", "192.168.1.2", "admin", "Password@_", "H3C HDM 公开默认值；首次登录后修改。", "H3C HDM published default; change it after first login.", "preset-h3c-hdm", now),
            Bmc("Cisco CIMC legacy default", "Cisco", "10.0.0.1", "admin", "password", "Cisco CIMC 旧版公开默认值；不同平台/版本可能变化。", "Legacy Cisco CIMC public default; verify by platform and firmware.", "preset-cisco-cimc", now),
            Bmc("Fujitsu iRMC reference", "Fujitsu", "192.168.0.120", "admin", "以机身标签/型号手册为准", "Fujitsu iRMC 默认值随型号变化，仅作公开资料索引。", "Fujitsu iRMC defaults vary by model; verify against the label or manual.", "preset-fujitsu-irmc", now),
            Bmc("ASRock Rack BMC reference", "ASRock Rack", "192.168.1.100", "admin", "以机身标签/型号手册为准", "ASRock Rack BMC 默认值随型号变化，仅作公开资料索引。", "ASRock Rack BMC defaults vary by model; verify against the label or manual.", "preset-asrockrack-bmc", now),
            Bmc("Tyan BMC reference", "Tyan", "192.168.1.100", "admin", "以机身标签/型号手册为准", "Tyan BMC 默认值随型号变化，仅作公开资料索引。", "Tyan BMC defaults vary by model; verify against the label or manual.", "preset-tyan-bmc", now)
        ];
    }

    private static FavoriteConfig Bmc(string name, string vendor, string targetIp, string user, string password, string description, string descriptionEn, string id, DateTime now) => new()
    {
        Id = id,
        Name = name,
        DeviceNumber = vendor,
        LocalIp = LocalHostFor(targetIp),
        SubnetMask = "255.255.255.0",
        TargetIp = targetIp,
        Username = user,
        Password = password,
        IsPublicDefault = true,
        Description = description + " / " + descriptionEn,
        MemoryText = "BMC public default preset. Verify model and change credentials after first login. / 带外公开默认模板，请核对型号并在首次登录后修改凭据。",
        CustomFields =
        [
            new FavoriteField { Name = "Type", Value = "BMC" },
            new FavoriteField { Name = "Vendor", Value = vendor },
            new FavoriteField { Name = "Open", Value = "http://" + targetIp },
            new FavoriteField { Name = "Credential source", Value = "Manufacturer public documentation / 厂商公开资料" }
        ],
        CreatedAt = now,
        UpdatedAt = now
    };

    private static string LocalHostFor(string targetIp)
    {
        var parts = targetIp.Split('.');
        if (parts.Length != 4) return "";
        var host = parts[3] == "1" ? "2" : "1";
        return $"{parts[0]}.{parts[1]}.{parts[2]}.{host}";
    }
}
